[profile.default]
solc-version = "0.8.8"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "csr-rewards/=lib/CSR-Rewards-ERC20/src/contracts/"
]
